---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: network-tools
spec:
  replicas: {{ $.Values.containersReplicas }}
  selector:
    matchLabels:
      app: network-tools
  template:
    metadata:
      labels:
        app: network-tools
        deployment: network-tools
      annotations:
        {{- if $.Values.additionalNetworks }}
        k8s.v1.cni.cncf.io/networks: {{ $.Values.additionalNetworks | join "," }}
        {{- end }}
    spec:
      containers:
        - name: network-tools
          image:  {{ $.Values.containersImage }}
          imagePullPolicy: IfNotPresent
          stdin: true
          stdinOnce: true
          command:
            - /bin/sh
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
